from pathlib import Path

from .config import resolve_directory_path


def create_markdown_file(filename: str, content: str, directory_path: str | None = None, overwrite: bool = False) -> str:
    """
    Creates a new markdown (.md) file with the specified content.
    Use this tool to save notes, documentation, or other text generated by the agent.

    Args:
        filename: The name of the file to create (e.g., 'new_note.md'). Will append .md if missing.
        content: The markdown text to write into the file.
        directory_path: Optional folder where the file will be saved. If omitted, uses the configured vault path.
        overwrite: If True, overwrites an existing file. If False, returns an error if the file exists.

    Returns:
        A success message with the file path, or an error message if creation fails.
    """
    if not filename.endswith('.md'):
        filename += '.md'

    resolved_directory = resolve_directory_path(directory_path)
    dir_path = Path(resolved_directory)

    try:
        dir_path.mkdir(parents=True, exist_ok=True)

        file_path = dir_path / filename

        if file_path.exists() and not overwrite:
            return f"Error: File '{filename}' already exists in '{resolved_directory}'. Set overwrite=True to replace it."

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        return f"Success: Created markdown file '{filename}' at '{dir_path}'."

    except Exception as e:
        return f"Error creating file: {str(e)}"