from .config import VaultPathError, resolve_vault_path, to_vault_relative


def create_markdown_file(path: str, content: str, overwrite: bool = False) -> str:
    """
    Creates a new markdown (.md) file inside the vault.
    Use this tool to save notes, documentation, or other text generated by the agent.

    Args:
        path: Vault-relative path for the new file, subfolders allowed
            (e.g. 'Portfolio Project/Azure DP900/New note.md'). '.md' is
            appended if missing. Missing parent folders are created inside
            the vault automatically.
        content: The markdown text to write into the file.
        overwrite: If True, overwrites an existing file. If False, returns an error if the file exists.

    Returns:
        A success message with the vault-relative file path, or an error message if creation fails.
    """
    rel_path = path if path.lower().endswith(".md") else f"{path}.md"

    try:
        file_path = resolve_vault_path(rel_path)
    except VaultPathError as e:
        return f"Error: {e}"

    if file_path.exists() and not overwrite:
        return (
            f"Error: File '{to_vault_relative(file_path)}' already exists. "
            "Set overwrite=True to replace it."
        )

    try:
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        return f"Success: Created markdown file at '{to_vault_relative(file_path)}'."
    except OSError as e:
        return f"Error creating file: {e}"
